name: Most Used Languages

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate Languages Chart
        uses: lowlighter/metrics@latest
        with:
          filename: languages.svg
          token: ${{ secrets.GHRS_GITHUB_API_TOKEN }}
          base: ""
          plugin_languages: yes
          repositories_forks: yes

          commits_authoring: asibo09, pietro.siboni3@studio.unibo.it, Pietro Siboni

          plugin_languages_indepth: yes
          plugin_languages_details: lines, percentage
          plugin_languages_limit: 12
          plugin_languages_sections: most-used
          plugin_languages_aliases: "Java:java"
